### ISSUE TITLE
Calling wipeandfree function from front-end using web3.js

### ISSUE THREAD

**Issue by techkrtk** [makerdao/dss#100]
In order interact with SaiProxy we need to execute that script through DSProxy of my account, right?
The function to be inkoved is `execute(address target, bytes data)` right?
When I did a transaction in kovan network from makerdao-cdp portal the encoded arugments of the wipeandfree are not matching with the number of arguments of execute() function.
Can anyone explain clearly what am I missing here and how to convert encoded functions arguments such as uint,address to bytes type since that is the datatype require in `execute()` functiona arguments.

**Comment by gbalabasquer** [comment]
Please come to chat.makerdao.com and write in #dev channel. Someone will pick up the question and try to help you.
I'm closing this issue as not related with `dss`.
