### ISSUE TITLE
Debt Auctions Can Be Blocked

### ISSUE THREAD

**Issue by kmbarry1** [makerdao/dss#108]
# Fixing Debt Auction Blocking

## Background

If surplus collected from a debt auction is canceled with free unbacked debt (`woe`) using `Vow.heal` instead of with on-auction debt (`Ash`) via `kiss`, future debt auctions (`flops`) can be prevented from occurring (see [these slides](https://docs.google.com/presentation/d/1nnpPBiOLEWi81q8zrHoIWH4s3iQaKrCSaR68AafzQJo/edit#slide=id.p) for an in-depth explanation; discussion occurred in [this governance call](https://youtu.be/erh25lnaIo0?t=376)). While governance can take action to unblock these debt auctions, it would be much better if the system either prevented this situation entirely or allowed it to be resolved without a governance vote.

## Primary Fix Options

While far from exhaustive, the options presented here cover what are probably the simplest and least disruptive fix options, and are thus the main ones under debate.

### Instant Access Module

When an amount `zed` of debt becomes "stuck" as `Ash`, governance can unblock the stuck debt by converting it into `woe` via calling first `Vat.suck(address(Vow), address(Vow), zed)` and then `Vow.kiss(zed)`. An appropriately permissioned (`relied` upon by the Vat) instant access module could enable this operation to be be done by anyone at any time, without requiring a governance vote.

The obvious attractive feature of this solution is that it requires no replacements of any existing core contracts. It is complicated, however, by the need to avoid "unsticking" auction debt that has not yet received a bid (otherwise extra, unnecessary debt auctions could occur). The simplest solution to this issue is to have the module keep track of how much debt is up for auction but as-of-yet unbid upon. This can be done without loops in the contract itself, for example as follows:

    // Define here mock interfaces for Vat, Vow, and Flopper.
    
    contract FlopUnblocker {
        // Define here obviously needed things like a constructor,
        // safe math functions, etc.
    
        Vat public vat;
        Vow public vow;
        Flopper public flop;
    
        mapping (uint => uint) public known;
        uint public knownAuctionCount;
        mapping (uint => uint) public ashes;
        uint public trueAsh;
    
        function unblock() public {
            require(knownAuctionCount == flop.kicks());
    
            // kiss away as much debt as possible
            uint joy = vat.dai(address(vow));
            require(joy < vow.Ash());  // optional: could instead kiss away Ash
            vow.kiss(joy);
    
            // unblock stuck auctions
            uint zed = sub(vow.Ash(), trueAsh);
            vat.suck(address(vow), address(vow), zed);
            vow.kiss(zed);
        }
    
        function update(uint id) public {
            require (id <= flop.kicks());
    
            if (known[id] == 0) {
                known[id] = 1;
                ++knownAuctionCount;
            }
    
            (uint bid,, address guy, uint48 tic,) = flop.bids(id);
    
            if (guy != address(0) && tic == 0) {
                // auction is active and unbid-upon
                if (ashes[id] == 0) {
                    trueAsh = add(trueAsh, bid);
                    ashes[id] = bid;
                }
            } else {
                // auction has received a bid
                trueAsh = sub(trueAsh, ashes[id]);
                ashes[id] = 0;
            }
        }
    }

Adding this module allows easy corrective action to be taken at any time, but it also increases the complexity of the system and carries a certain amount of technical risk (primarily since it requires authorization against the Vat and calls `suck`). It also enshrines managing "stuck" debt as a permanent cognitive overhead for ecosystem participants (although likely in the long-term automation logic, e.g. in Keeper bots, would reduce this overhead to near-zero).

### Call `kiss` Upon First `dent`

This constitutes adding the following logic just after the call to `Vat.move` in `dent`:

    if (bids[id].tic == 0) {
        Vow vow = Vow(bids[id].guy);  // first guy = gal = Vow
        uint rad = vow.Ash() >= bid ? bid : vow.Ash();
        vow.kiss(rad);
    }

The advantage of this solution is its simplicity and obvious correctness.

The major downside is the need to replace the Flopper contract, which can break other deployed smart contracts and require updates to UIs, Keepers, and other off-chain software.

Minor downsides include slightly increased gas costs for `dent`, and a slightly higher gas cost for the first `dent` as compared to subsequent `dents` in a given auction.

There is also an architectural inelegance—the Vow is dependent on the Flopper behaving in a certain way to ensure correct debt handling.

### `heal` Reverts If `Ash` Is Non-zero

While this trivially prevents `flops` from being blocked by requiring `Ash` to be eliminated via `kiss` before `healing` can take place, it requires replacing the Vow, a much more risky modification to the system than either replacing the Flopper or adding an instant access module. It also has some probability of breaking contracts or Keepers that do not prioritize `kissing` debt over `healing` debt (not to mention upgrades and updates of contracts and bots that depend on the Vow's address). It is, however, architecturally pure—the Vow can behave correctly regardless of how other contracts or users call its unauthorized functions.

### Re-Architect Debt Auction Interactions

E.g., have the Flopper receive the dai bids, only transfer to the Vow on `deal`, and make `kiss` only callable by the Flopper itself (which it would do during `deal`). This is a structurally pleasing option in that it makes `flop` mechanics more similar to those of `flap`, but replacing both the Vow and the Flopper while invalidating a lot of Keeper code is probably not prudent since the system is already live. It also couples the Vow and Flopper more tightly than is necessarily wise. There's more design space here, but there's not a lot of point in exploring it given that the system is already deployed and thus minimizing change is preferable.

**Comment by brianmcmichael** [comment]
As this is not a critical bug I'd suggest a two-part approach.

First would be to deploy the instant access module. This solution is not the most elegant, but it can be bolted-on to the existing system without redeployment of a core contract, so it is the least disruptive.

Second, perform the modification to the Flopper contract in dss, so if another more serious bug is discovered or the system is redeployed for alternative currencies it will be included in that redeployment.

Other solutions may arise in the longer-term if we consider redesigning the auction systems.

**Comment by kmbarry1** [comment]
As far as having fixes in the system for if it gets redeployed--having `Vow.heal` revert if `Ash != 0` is massively preferable in that case. We should probably bifurcate `dss` into "deployed system" and "version for clean redeployments" repos or branches.

Regarding how to fix the live system--I am not convinced that replacing at least the Flopper is an infeasible operation. Further, the instant access module is non-trivial and will require significant testing and verification to ensure that it operates safely under all conditions. That cost+risk should be weighed against the cost of replacing the Flopper (note that the Flopper fix is dead simple, almost impossible to mess up). And some thought should be given to a Vow upgrade as well, for completeness, even if just to prove that that option really is undesirable from a technical risk perspective.

**Comment by brianmcmichael** [comment]
I don't think I can argue against the Flopper upgrade as long as it is not in use at the time.

**Comment by gbalabasquer** [comment]
It doesn't matter the old flopper is still in use. It can be changed by the new one and the on going auctions will end without any issue.
@kmbarry1 do you want to send a PR for the `flop` fix or do you prefer I take care of it?

**Comment by godsflaw** [comment]
I am in support of the flopper fix.  Happy to review once we have it.

**Comment by kmbarry1** [comment]
@gbalabasquer I don't care too much who does the work, so long as we are in agreement over the correct path to take. The reason I have been holding off is to see what feedback or discussion might occur. Since it seems strong support for fixing via the Flopper is emerging, I will implement it in a day or two if there are no strong objections.

**Comment by gbalabasquer** [comment]
Sounds good.

**Comment by gbalabasquer** [comment]
This was fixed in linked PR.
