### ISSUE TITLE
Jug.base does not conform to standard rate calculation

### ISSUE THREAD

**Issue by brianmcmichael** [makerdao/dss#112]
The `base` variable in [jug.sol](https://github.com/makerdao/dss/blob/master/src/jug.sol) does not conform to the standard values we use for `duty`.  

Currently we calculate `duty` values at the command line using 
```
# (example 8%)
$ bc -l <<< 'scale=27; e( l(1.08)/(60 * 60 * 24 * 365) )'
> 1.000000002440418608258400030
```
  where the result `1.000000002440418608258400030` is stored as a `ray` (example: `1000000002440418608258400030`). This calculation works for both the individual collateral `duty` values as well as the `dsr` rate. This rate calculation will not apply to the `base` value in jug as the system is configured.

Currently, the system `base` value is `0`, which works because `base` is added to the `ilk.duty` in [drip()#104](https://github.com/makerdao/dss/blob/master/src/jug.sol#L104). Replacing this with a base rate value based on the duty calculation (ex. `1000000002440418608258400030` causes a revert in testing. Due to this rate calculation in drip, the base rate instead needs to be a smaller number, with a full `RAY` value subtracted, like `2440418608258400030`, due to the addition operation. Even then, it's not as simple to calculate the base due to the compounding factors. Adding these two values will not produce an accurate compounded rate, for example:

```
// 8% duty calculation
eight_pct_duty                 = 1000000002440418608258400030

// example 1% base + 7% duty
one_pct_duty                   = 1000000000315522921573372069
seven_pct_duty                 = 1000000002145441671308778766
one_pct_duty + seven_pct_duty == 2000000002460964592882151000

// results are not equivalent
eight_pct_duty != (one_pct_duty + seven_pct_duty) - 10**27

```

The system works as expected with a `base` of 0, but I'm not sure the rates will operate as expected with a different `base` value. Any modification to `base` will need a new calculation that accounts for the `drip()` function not subtracting a `RAY` value from the added rates, and also accounts for the discrepancy in adding the `base + duty` compounded values.

**Comment by kmbarry1** [comment]
This is not an issue with the `dss` codebase. There is nothing written in stone about how we calculate values. If we ever start using `base` (which I kinda suspect we won't, tbh), yes, we'll need to change how the values are calculated. There is nothing hard about this.

**Comment by brianmcmichael** [comment]
This isn't about whether it's hard but whether it's expected. I think it's an assumption that this base value will follow the same rate calculation as the other rate mechanisms in the system. This clearly does not and it needs to be recognized for any governance actions to modify that base.

**Comment by kmbarry1** [comment]
There is no such assumption (at least not in the `dss` system, it doesn't calculate rates, it just takes them as inputs). If governance is too incompetent to do trivial math, the system has bigger issues.

**Comment by brianmcmichael** [comment]
`base` is undocumented and governance will be working on patterns. This is not addressed in either the MCD documentation or the Rate Module documentation. While the math may be trivial here, I am not comfortable writing off this issue until the documentation reflects that this value is fundamentally different than other rate values in the system.

**Comment by brianmcmichael** [comment]
I think the real issue may be obscured in the above, but the thing that everyone needs to be clear on is that a `duty` needs to be `>=10**27`, but a `base` needs to be `<10**27`. That's not clear in the code or the documentation.

**Comment by kmbarry1** [comment]
I have no objection to adding a note or example for this to the Jug documentation, that's a good thing to do, this just isn't an issue with the codebase itself. Even if we added a `- RAY` to `base + duty`, the correct way to add per-second rates is still non-linear, so there's no real gain, it actually just makes it more complicated.

Also:
> a `duty` needs to be `>=10**27`, but a `base` needs to be `<10**27`
isn't true. You could just as well take the opposite convention, which arguably makes more sense (that way, if `duty == 0`, `base` still guarantees a non-negative rate). But really so long as `base + duty` for each collateral comes out to the correct per-second value, you can use whatever convention you like. E.g. you could fix `base` at `10**27` and then choose `duty` appropriately.

**Comment by brianmcmichael** [comment]
`duty` is presumed to be the higher value, when initializing a new ilk, the `duty` is set to `10**27` at https://github.com/makerdao/dss/blob/master/src/jug.sol#L83

**Comment by kmbarry1** [comment]
That's not a conclusion you can draw from that line of code.

**Comment by brianmcmichael** [comment]
We disagree.

**Comment by kmbarry1** [comment]
All that line of code does is guarantee that the initial rate for a collateral is not negative. It has to do that via `duty` because changing `base` would affect other collateral types. Arguably it could take `base` into account, but realistically, when adding a collateral, governance will want to set a custom value for `duty` in the same spell anyway, so it doesn't really matter. (Also a good thing for the documentation, but not a code issue.)

It in no way implies "`duty` must always be greater than `10**27`", because the contract does not enforce that invariant.

**Comment by brianmcmichael** [comment]
If base is set to `>=10**27` and a new ilk is initialized at `10**27`, that ilk will immediately begin to fail on drip transactions because the combined rate will be `>=2*(10**27)`. While the duty can be immediately updated to something else to satisfy the formula, it's something that is undocumented and arguably unexpected.

**Comment by kmbarry1** [comment]
There's no `require(data >= 10**27);` in `file` for `duty`. There's nothing wrong with a `base < 10**27` convention, but the code doesn't enforce it.

**Comment by kmbarry1** [comment]
We're arguing over the difference between "this is a logical way to do things that plays nicely with `init`" and "things absolutely must be done this way".
