### ISSUE TITLE
Expose liquidation penalty as a public function 

### ISSUE THREAD

**Issue by yaronvel** [makerdao/dss#134]
I would kindly ask that the cat would expose the tab calculation as a public function.
A similar function exists in compound as an API (in their smart contract).
A PR was submitted https://github.com/makerdao/dss/pull/133

The motivation is that we are working on an opt-in liquidation system that needs to read the liquidation penalty value from makerdao’s `cat`.
We plan to read the cat address from the `end` contract, but changes like in this version, where the `chop` resolution changed from `rad` to `wad` will break our system (in the future, it is still not deployed).
Hence, a function that for a given `art` returns the tab, would really help.

**Comment by gbalabasquer** [comment]
Replied in the PR.
