### ISSUE TITLE
How to calculate total collateral for an ilk

### ISSUE THREAD

**Issue by levity** [makerdao/dss#23]
With the removal of `Ilk.Ink` in `vat.sol`, how should we now calculate the total amount of collateral locked up in CDPs for an ilk?

**Comment by rainbreak** [comment]
It depends on what you need exactly. `ilk.Ink` was removed as it isn't safety critical and also doesn't represent "backing collateral" as you can have a CDP with zero debt.

For the total collateral in a specific ilk you can look at the adapter balance. For the specific amount that is locked (but not necessarily backing anything) you'd now have to process events or use vdb. @desaperados
