### ISSUE TITLE
Oasis does not work when using MetaMask with local full node

### ISSUE THREAD

**Issue by the-metalworker** [makerdao/dss#232]
I am using the Oasis app at https://oasis.app/dashboard which I found on https://makerdao.com.

My issue is that when I connect to Oasis I get this error:

> Browser ethereum provider and URL network param do not match!"

I am using MetaMask, connected to my own local full node running on Localhost 8545. When I switch MetaMask from "Localhost" network to "Mainnet", "Trust Infura" mode, then Oasis will work as expected. Something about the way Oasis is connecting to MetaMask doesn't work when I use Oasis and MetaMask connected to my own local full node instead of Infura, although it should work and there are other Ethereum apps I use that do work with my full node.

Sorry if this is the wrong place to post this issue. Even though the Oasis FAQ says the app is open source I could not find a repo for the Oasis app anywhere. This seemed like the next best place.

> Is Oasis Secure?
> Security is our top priority. We stringently follow the best security practices, and regularly conduct smart contract and code audits. In addition, Oasis code is open-source, giving everyone in the community the ability to pressure test and audit the core technology.

Source: https://oasis.app/support

**Comment by gbalabasquer** [comment]
This issue doesn't correspond to this repo. You can contact the oasis support in https://discord.gg/oasisapp
