### ISSUE TITLE
Hey old investor and holder with smart contracts helping and old project with security 

### ISSUE THREAD

**Issue by philipjonsen** [makerdao/dss#248]
You have multiple vulns in your code and python and unupdated os. Also in smart contracts, 

makerdao/market-maker-keeper 
83
C
261
H
291
M
468
L
83
C
260
H
286
M
468
L

Sol: Hardcoded [value]() is used as a [cipher key (in ethereumjs-util.privateToAddress)](). Generate the value with a cryptographically strong random number generator and do not hardcode it in source code. get back to me so i help you and fix this. 

best regards Philip cyptocurrencies sweden

**Comment by gbalabasquer** [comment]
I guess you mean about [generateSig.js](https://github.com/makerdao/dss/blob/master/scripts/generateSig.js).
Have you checked what this file is used for?

**Comment by philipjonsen** [comment]
Hey! No, I just did a quick search and found a lot of vulns. can check it
out :)

Den fre 11 feb. 2022 kl 12:43 skrev Gonzalo Balabasquer <
***@***.***>:

**Comment by philipjonsen** [comment]
The contracts is a multisig (multisignature) contractsthat need to be
validated by all parties to be able to use the contract.

Den fre 11 feb. 2022 kl 13:45 skrev Philip Jonsén ***@***.***>:

**Comment by philipjonsen** [comment]
these wallets can verify the dai stablecoin contract and use it
const del = new Buffer.from('dd2d5d3f7f1b35b7a0601d6a00dbb7d44af58479',
'hex');
const dai = new Buffer.from('11Ee1eeF5D446D07Cf26941C7F2B4B1Dfb9D030B',
'hex');

Den fre 11 feb. 2022 kl 13:46 skrev Philip Jonsén ***@***.***>:

**Comment by philipjonsen** [comment]
its encrypted in hex now, but you can decrypt them.
also not so got that privkey is visible
4af1bceebf7f3634ec3cff8a2c38e51178d5d4ce585c52d6043e5e2cc3418bb0

Den fre 11 feb. 2022 kl 13:47 skrev Philip Jonsén ***@***.***>:

**Comment by philipjonsen** [comment]
Its also encrypted in hex, but easy to decrypt.

Den fre 11 feb. 2022 kl 13:49 skrev Philip Jonsén ***@***.***>:

**Comment by gbalabasquer** [comment]
It is just to generate addresses for the solidity tests.

**Comment by philipjonsen** [comment]
should i decrypt the addresses? is those who stole your funds?

Den fre 11 feb. 2022 kl 13:51 skrev Philip Jonsén ***@***.***>:

**Comment by philipjonsen** [comment]
Ok


Den fre 11 feb. 2022 kl 12:52 skrev Gonzalo Balabasquer <
***@***.***>:

**Comment by philipjonsen** [comment]
Do you want the full report and what to fix?

Den fre 11 feb. 2022 kl 13:53 skrev Philip Jonsén ***@***.***>:

**Comment by philipjonsen** [comment]
I can also do some real checks on your sites, and servers, with
persmisssion of course. but that takes time and costs money

Den fre 11 feb. 2022 kl 13:56 skrev Philip Jonsén ***@***.***>:

**Comment by philipjonsen** [comment]
are you running any apache on any of your servers?

Den fre 11 feb. 2022 kl 13:58 skrev Philip Jonsén ***@***.***>:

**Comment by philipjonsen** [comment]
I did I cant right now, i can only post 5 bugs.

Den fre 11 feb. 2022 kl 13:17 skrev Gonzalo Balabasquer <
***@***.***>:

**Comment by philipjonsen** [comment]
Need to wait 48 hours.

Den fre 11 feb. 2022 kl 14:25 skrev Philip Jonsén ***@***.***>:

**Comment by philipjonsen** [comment]
Shall i wait 48hours to post them or do you want them now?

Den fre 11 feb. 2022 kl 14:44 skrev Philip Jonsén ***@***.***>:
