### ISSUE TITLE
Reentrancy detected 

### ISSUE THREAD

**Issue by L-KH** [makerdao/dss#56]
Reentrancy in Flopper.deal(uint256) (flop.sol#133-139):                              
        External calls:                                                              
        - gem.mint(bids[id].guy,bids[id].lot) (flop.sol#137)                         
        State variables written after the call(s):                                   
        - bids (flop.sol#138)                                                        
Reentrancy in Flopper.dent(uint256,uint256,uint256) (flop.sol#117-132):              
        External calls:                                                              
        - vat.move(msg.sender,bids[id].guy,bid) (flop.sol#127)                       
        State variables written after the call(s):                                   
        - bids (flop.sol#129)                                                        
        - bids (flop.sol#130)                                                        
        - bids (flop.sol#131)                                                        
Reentrancy in Flopper.yank(uint256) (flop.sol#144-149):                              
        External calls:                                                              
        - vat.move(address(this),bids[id].guy,bids[id].bid) (flop.sol#147)           
        State variables written after the call(s):                                   
        - bids (flop.sol#148)                                                        
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#reentrancy-vulnerabilities-1

**Comment by livnev** [comment]
These are all false positives: the external calls are to known contracts, and there is no possibility of reëntrancy there.
