### ISSUE TITLE
Change the order of operations in pot

### ISSUE THREAD

**Issue by MicahZoltu** [makerdao/dss#86]
https://github.com/makerdao/dss/blob/effdda3657f71fd6efc3465dc661b375d1bacc3e/src/pot.sol#L149-L151

While I don't _think_ there is a specific reentrancy attack here, it is not recommended to update the balance first and _then_ move the underlying asset.  Instead, you should move the underlying asset first, then after that is successful update the balance.

**Comment by MrChico** [comment]
The behaviour of `vat.move` is known and there is no risk of reentrancy here
