### ISSUE TITLE
Add require messages to all require statements.

### ISSUE THREAD

**Issue by MicahZoltu** [makerdao/dss#97]
Trying to integrate with Maker is proving to be quite the chore because _many_ of the require calls contain no message, which means when a transaction fails it is for an opaque reason.  If each of the require statements contained a unique message (even if it was just file/line number) then it would be much easier to debug failures.

**Comment by gbalabasquer** [comment]
Hey, have you checked the latest version? https://github.com/makerdao/dss/commit/6fa55812a5fcfcfa325ad4d9a4d0ca4033c38cab

**Comment by MicahZoltu** [comment]
Ah, sneaky buggers.  I was using the version from _yesterday_.

**Comment by MicahZoltu** [comment]
I will re-open if I find any missing after updating to latest.

**Comment by gbalabasquer** [comment]
There are some missing messages (for internal functions) as that brings issues with the formal verification proofs. Those will remain as they are.
